import {characters,questions,VERSION,calculate,resultFrom,validateSubmission} from './core.js';
const app=document.querySelector('#app'),audio=document.querySelector('#reveal-audio');
const $=s=>document.querySelector(s);
const uuid=()=> '10000000-1000-4000-8000-100000000000'.replace(/[018]/g,c=>(c^crypto.getRandomValues(new Uint8Array(1))[0]&15>>c/4).toString(16));
const portrait=c=>`<div class="portrait c${c.id}"><img src="assets/${c.id}.jpg" alt="${c.name}" width="220" height="240"></div>`;
const readDraft=()=>{try{const d=JSON.parse(sessionStorage.getItem('yellow-draft'));return d?.version===VERSION&&Array.isArray(d.answers)&&d.answers.length===12&&d.answers.every(x=>x===null||Number.isInteger(x)&&x>=0&&x<4)&&Number.isInteger(d.index)&&d.index>=0&&d.index<12?d:null;}catch{return null;}};
let draft=readDraft(),answers=Array(12).fill(null),index=0,records=[],current=null,pending=null,saveState='',view='home',busy=false,requestTicket=0;
try { const p=JSON.parse(sessionStorage.getItem('yellow-pending')); if(p){validateSubmission(p);pending=p;current={...p,...resultFrom(p.answers,p.chosen),createdAt:p.createdAt};saveState='error';} } catch {}
function toast(message){$('#toast').textContent=message;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',3500);}
function focusMain(){app.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}
function writeDraft(){draft={version:VERSION,answers,index};try{sessionStorage.setItem('yellow-draft',JSON.stringify(draft));}catch{}}
function clearDraft(){draft=null;try{sessionStorage.removeItem('yellow-draft');}catch{}}
async function request(path,options={}){const response=await fetch(path,{...options,credentials:'same-origin',signal:AbortSignal.timeout(12000),headers:{'Content-Type':'application/json',...options.headers}});const data=await response.json();if(!response.ok)throw new Error(data.error||'请求暂时失败，请重试。');return data;}
function navigate(next){location.hash=next;}
function stopAudio(){audio.pause();audio.currentTime=0;}
function home(){view='home';stopAudio();app.innerHTML=`<section class="home-grid"><div class="intro"><div class="eyebrow">YELLOW CREATURE TEST</div><span class="stamp">人类，暂停一下。</span><h1>你的本体，<br>是哪只<br><mark>黄色生物？</mark></h1><p class="intro-copy">有人嘴替，有人淡定，有人天生很抽象。<br>12 个小场面，让你的隐藏物种露个脸。</p><button class="primary start" id="start-button">开始鉴定我的本体</button><p class="small-note">约 2—3 分钟 · 凭第一反应 · 没有标准答案</p>${draft?`<div class="resume">上次答到第 ${draft.index+1} 题。<button class="text-button" id="resume-button">接着测</button></div>`:''}</div><div class="specimens"><div class="board-head"><b>本期在逃生物</b><span>06 SPECIMENS / 请对号入座</span></div><div class="cards">${characters.map(c=>`<div class="specimen"><span class="number">${c.id}</span>${portrait(c)}<b>${c.name}</b><em>${c.tag}</em></div>`).join('')}</div><div class="board-foot">看起来都很黄，脑回路各有各的忙。</div></div></section><div class="micro-line"><span><b>12</b> 个日常小场面</span><span><b>06</b> 只黄色生物</span><span><b>100%</b> 娱乐用途</span></div>`;$('#start-button').onclick=()=>start(false);if($('#resume-button'))$('#resume-button').onclick=()=>start(true);}
function start(resume){if(resume&&draft){answers=[...draft.answers];index=draft.index;}else{answers=Array(12).fill(null);index=0;}current=null;stopAudio();writeDraft();if(location.hash==='#quiz'){quiz();focusMain();}else navigate('quiz');}
function quiz(){view='quiz';const q=questions[index];app.innerHTML=`<section class="quiz-wrap"><div class="quiz-head"><button class="text-button" id="prev">${index?'上一题':'返回首页'}</button><span>本体鉴定中 <b>${String(index+1).padStart(2,'0')}</b> / 12</span></div><div class="progress" role="progressbar" aria-label="答题进度" aria-valuemin="0" aria-valuemax="12" aria-valuenow="${index}"><span style="width:${index/12*100}%"></span></div><span class="question-no">SCENE ${String(index+1).padStart(2,'0')}</span><h2 class="question-title" id="question-heading">${q.title}</h2><p class="question-sub">${q.hint}</p><div class="options" role="group" aria-labelledby="question-heading">${q.options.map(([t],i)=>`<button class="option ${answers[index]===i?'selected':''}" aria-pressed="${answers[index]===i}" data-choice="${i}"><span class="option-letter">${'ABCD'[i]}</span><span>${t}</span></button>`).join('')}</div><div class="quiz-bottom"><span class="small-note">选最像自己的那个。<br>${index===11?'揭晓时会播放结算音效。':'不必想太久，本体会带路。'}</span><button class="primary" id="next" ${answers[index]===null?'disabled':''}>${index===11?'揭晓我的本体':'下一题'}</button></div></section>`;
 document.querySelectorAll('[data-choice]').forEach(button=>button.onclick=()=>{answers[index]=+button.dataset.choice;writeDraft();document.querySelectorAll('[data-choice]').forEach(b=>{const selected=+b.dataset.choice===answers[index];b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',selected);});$('#next').disabled=false;});
 $('#prev').onclick=()=>{if(index){index--;writeDraft();quiz();focusMain();}else navigate('home');};
 $('#next').onclick=()=>{if(answers[index]===null)return;if(index<11){index++;writeDraft();quiz();focusMain();}else finish();};
}
function finish(chosen){const result=calculate(answers);if(!chosen&&result.tied.length>1){view='tie';app.innerHTML=`<section class="quiz-wrap"><span class="question-no">隐藏分支 / MIXED FLAVOR</span><h2 class="question-title">你身上住着不止一只。</h2><p class="question-sub">这几只和你同样接近。凭直觉，认领今天更像你的那只。</p><div class="tie-cards">${result.tied.map(id=>{const c=characters.find(x=>x.id===id);return `<button data-tie="${id}">${portrait(c)}<b>${c.name}</b><p>${c.tag}<br>${c.quote}</p></button>`;}).join('')}</div><button class="text-button" id="tie-back">回去修改答案</button></section>`;document.querySelectorAll('[data-tie]').forEach(b=>b.onclick=()=>finish(b.dataset.tie));$('#tie-back').onclick=quiz;focusMain();return;}
 pending={id:uuid(),version:VERSION,answers:[...answers],chosen:chosen||result.tied[0]};current={...pending,...resultFrom(answers,pending.chosen),createdAt:new Date().toISOString()};saveState='saving';try{sessionStorage.setItem('yellow-pending',JSON.stringify({...pending,createdAt:current.createdAt}));}catch{}clearDraft();view='result';history.replaceState(null,'','#result');renderResult();focusMain();playAudio(true);saveResult();}
async function saveResult(){if(!pending||busy)return;busy=true;const payload=pending;try{const data=await request('/api/results',{method:'POST',body:JSON.stringify(payload)});records=[data.result,...records.filter(r=>r.id!==data.result.id)];$('#history-count').textContent=`(${records.length})`;if(current?.id===data.result.id){current=data.result;saveState='saved';}if(pending?.id===payload.id){pending=null;try{sessionStorage.removeItem('yellow-pending');sessionStorage.setItem('yellow-current',JSON.stringify(current));}catch{}}}catch{if(current?.id===payload.id)saveState='error';}finally{busy=false;updateSave();if(pending&&pending.id!==payload.id)saveResult();}}
function updateSave(){const el=$('#save-status');if(!el||view!=='result')return;el.innerHTML=saveState==='saved'?'已保存到我的记录 · 同一浏览器可回看':saveState==='saving'?'正在保存这次鉴定…':'结果已生成，但记录暂未保存。<button class="text-button" id="retry-save">重试保存</button>';if($('#retry-save'))$('#retry-save').onclick=()=>{saveState='saving';updateSave();saveResult();};}
const dimensionLabels=['表达方式','行动节奏','应变方式','快乐补给'];
const dimensionEnds=[['内置弹幕','现场广播'],['先看一眼','先动一下'],['换条路线','认准再推'],['自助充电','拉人联机']];
function renderResult(){if(!current){navigate('history');return;}view='result';const c=characters.find(x=>x.id===current.character);app.innerHTML=`<section class="result-layout reveal-in"><div class="result-poster"><div class="eyebrow">YOUR YELLOW IDENTITY</div><h1>${c.name}</h1><span class="tag">${c.tag}</span>${portrait(c).replace('class="portrait','class="portrait result-portrait')}<p class="result-quote">“${c.quote}”</p><div class="poster-bottom"><span>黄色生物研究所</span><span>NO. ${c.id} / 娱乐鉴定</span></div></div><div class="result-details"><a class="back-link" href="#home">回到研究所</a><h2>${c.headline}</h2><p>${c.description}</p><div class="evidence">${current.vector.map((v,i)=>`<div class="trait"><span>${dimensionLabels[i]}</span><strong>${v<2.7?dimensionEnds[i][0]:v>3.3?dimensionEnds[i][1]:'看场合切换'}</strong></div>`).join('')}</div>${current.mixed?`<p class="small-note">混合口味：还带一点 ${characters.find(x=>x.id===current.secondary).name} 的气质。</p>`:''}<div class="tip"><b>一点可爱的小毛病</b>${c.quirk}<br><b style="margin-top:12px">今天的生存建议</b>${c.tip}</div><div class="result-actions"><button class="primary" id="save-card">保存结果卡</button><button class="secondary" id="again">再测一次</button></div><div class="audio-row"><button id="audio-toggle">播放结算音效</button><span id="audio-status">音效随时可暂停</span></div><div id="save-status" class="save-status" role="status"></div><a class="text-button small-note" href="#history">看看之前测出了什么</a></div></section>`;$('#again').onclick=()=>start(false);$('#save-card').onclick=saveCard;$('#audio-toggle').onclick=()=>{if(!audio.paused){audio.pause();updateAudio();}else playAudio(audio.ended);};updateAudio();updateSave();}
function updateAudio(){const b=$('#audio-toggle');if(b)b.textContent=audio.paused?(audio.currentTime>0&&!audio.ended?'继续播放':'播放结算音效'):'暂停音效';}
function playAudio(restart=false){if(restart)audio.currentTime=0;const promise=audio.play();if(promise)promise.then(()=>{updateAudio();const el=$('#audio-status');if(el)el.textContent='本体出场，自带配乐';}).catch(()=>{updateAudio();const el=$('#audio-status');if(el)el.textContent='点左侧按钮播放音效';});}
['pause','play','ended'].forEach(event=>audio.addEventListener(event,updateAudio));audio.addEventListener('error',()=>{if($('#audio-status'))$('#audio-status').textContent='音频暂时无法加载，请稍后再试';});
function dateLabel(date){return new Date(date).toLocaleString('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});}
async function historyView(){view='history';stopAudio();const ticket=++requestTicket;app.innerHTML=`<section class="history-wrap"><a class="back-link" href="#home">回到研究所</a><h1 class="history-title">我的变黄记录</h1><p class="small-note">记录保存在服务端，通过当前浏览器识别你。清除网站数据或更换设备后，无法直接找回。展示最近 100 次。</p><div id="history-body" aria-live="polite"><div class="empty">正在翻找你的生物档案…</div></div></section>`;try{const data=await request('/api/results');records=data.results;$('#history-count').textContent=`(${records.length})`;if(view!=='history'||ticket!==requestTicket)return;$('#history-body').innerHTML=records.length?`<div class="history-list">${records.map((r,i)=>{const c=characters.find(c=>c.id===r.character);return `<button class="history-item" data-record="${i}">${portrait(c)}<span><strong>${c.name}</strong><time>${dateLabel(r.createdAt)}</time></span><span class="history-tag">${c.tag}</span></button>`;}).join('')}</div><button class="secondary" id="export-records">导出我的记录</button>`:`<div class="empty"><h2>暂时还是人类。</h2><p>完成一次测试，你的黄色生物档案就会出现在这里。</p><button class="primary" id="empty-start">去测一下</button></div>`;document.querySelectorAll('[data-record]').forEach(b=>b.onclick=()=>{current=records[+b.dataset.record];saveState='saved';try{sessionStorage.setItem('yellow-current',JSON.stringify(current));}catch{}navigate('result');});if($('#empty-start'))$('#empty-start').onclick=()=>start(false);if($('#export-records'))$('#export-records').onclick=()=>download(new Blob([JSON.stringify(records,null,2)],{type:'application/json'}),'我的黄色生物记录.json');}catch{if(view==='history'&&ticket===requestTicket){$('#history-body').innerHTML='<div class="empty"><p>档案暂时没翻出来，请检查网络后重试。</p><button class="secondary" id="retry-history">重新加载</button></div>';$('#retry-history').onclick=historyView;}}}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
async function saveCard(){const c=characters.find(x=>x.id===current.character);const b=$('#save-card');b.disabled=true;try{const canvas=document.createElement('canvas');canvas.width=750;canvas.height=1080;const ctx=canvas.getContext('2d');ctx.fillStyle='#ffe239';ctx.fillRect(0,0,750,1080);ctx.strokeStyle='#22241e';ctx.lineWidth=4;ctx.strokeRect(28,28,694,1024);ctx.fillStyle='#22241e';ctx.textAlign='center';ctx.font='bold 22px sans-serif';ctx.fillText('黄色生物研究所 / 我的本体',375,88);ctx.font='900 72px sans-serif';ctx.fillText(c.name,375,197);ctx.font='bold 32px sans-serif';ctx.fillText(c.tag,375,260);const img=new Image();img.src=`assets/${c.id}.jpg`;await img.decode();ctx.save();ctx.beginPath();ctx.roundRect(115,310,520,490,40);ctx.clip();ctx.fillStyle='#fffef6';ctx.fillRect(115,310,520,490);let sx=0,sy=0,sw=img.naturalWidth,sh=img.naturalHeight;if(c.id==='06')sw=sw*.345;if(c.id==='02')sh=sh*.76;if(c.id==='05'){sx=sw*.27;sy=sh*.2;sw*=.46;sh*=.55;}const ratio=Math.min(520/sw,490/sh),w=sw*ratio,h=sh*ratio;ctx.drawImage(img,sx,sy,sw,sh,115+(520-w)/2,310+(490-h)/2,w,h);ctx.restore();ctx.fillStyle='#22241e';ctx.font='bold 30px sans-serif';ctx.fillText(c.quote,375,876);ctx.font='22px sans-serif';ctx.fillText('12 个小场面，测测你是哪只黄色生物。',375,936);ctx.font='18px sans-serif';ctx.fillText(dateLabel(current.createdAt)+' · 纯属娱乐',375,1001);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw Error();download(blob,`黄色生物-${c.name}.png`);toast('结果卡已生成，可在下载中查看；也可以直接截图。');}catch{toast('暂时无法保存图片，可以截图留住你的本体。');}finally{b.disabled=false;}}
function route(){const page=location.hash.slice(1);if(page==='result'&&!current){try{const r=JSON.parse(sessionStorage.getItem('yellow-current'));if(r&&characters.some(c=>c.id===r.character)){current=r;saveState='saved';}}catch{}}if(page==='quiz'){if(draft){answers=[...draft.answers];index=draft.index;}quiz();}else if(page==='history')historyView();else if(page==='result'&&current)renderResult();else home();focusMain();}
$('#history-button').onclick=()=>{if(location.hash==='#history')historyView();else navigate('history');};window.addEventListener('hashchange',route);window.addEventListener('pagehide',()=>audio.pause());route();
// 仅在浏览器支持时提供与页面一致的读取和导航能力。
if(document.modelContext?.registerTool){for(const tool of [{name:'read_quiz_state',title:'查看测试状态',description:'读取当前测试页面与答题进度，不修改答案。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({view,question:view==='quiz'?index+1:null,answered:answers.filter(a=>a!==null).length,result:view==='result'?current?.character:null})},{name:'open_quiz_history',title:'打开测试记录',description:'打开当前浏览器对应的历史记录页面。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:async input=>{if(input&&Object.keys(input).length)throw Error('不接受额外参数');history.replaceState(null,'','#history');await historyView();return {view,loaded:!!$('#history-body .history-list')||records.length===0};}}]){try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{});}catch{}}}


