import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {questions,characters,calculate,resultFrom,VERSION} from '../public/core.js';
import {api} from '../api.mjs';
test('four equally weighted dimensions, three questions each',()=>{assert.deepEqual([0,1,2,3].map(d=>questions.filter(q=>q.d===d).length),[3,3,3,3]);for(const q of questions)assert.deepEqual(q.options.map(o=>o[1]).sort(),[1,2,4,5]);});
test('all six creatures can be uniquely reached; ties can be explicitly claimed',()=>{const sums=new Map();for(let a=0;a<4;a++)for(let b=0;b<4;b++)for(let c=0;c<4;c++){const v=[1,2,4,5];sums.set(v[a]+v[b]+v[c],[v[a],v[b],v[c]]);}const combos=[...sums.values()],seen=new Set();let tied;for(const a of combos)for(const b of combos)for(const c of combos)for(const d of combos){const offsets=[0,0,0,0],dims=[a,b,c,d],answers=questions.map(q=>{const value=dims[q.d][offsets[q.d]++];return q.options.findIndex(o=>o[1]===value);});const score=calculate(answers);if(score.tied.length===1)seen.add(score.tied[0]);else if(!tied)tied={answers,score};}assert.equal(seen.size,6);assert.ok(tied);const selected=tied.score.tied.at(-1);assert.equal(resultFrom(tied.answers,selected).character,selected);assert.throws(()=>resultFrom(tied.answers,characters.find(c=>!tied.score.tied.includes(c.id)).id));});
test('malformed or incomplete answers are rejected',()=>{for(const a of [[],Array(12).fill(null),Array(12).fill(4),Array(12).fill('1'),null])assert.throws(()=>calculate(a));assert.deepEqual(calculate(Array(12).fill(0)),calculate(Array(12).fill(0)));});
function database(){const sql=new DatabaseSync(':memory:');sql.exec(readFileSync(new URL('../drizzle/0000_silent_fixer.sql',import.meta.url),'utf8'));return {prepare(query){return{bind(...args){const s=sql.prepare(query);return{async all(){return{results:s.all(...args)};},async first(){return s.get(...args)||null;},async run(){return s.run(...args);}};}};}};}
const base='http://localhost:4173/api/results';
const payload={id:'12345678-1234-4234-8234-123456789012',version:VERSION,answers:Array(12).fill(0)};
test('database persists records, isolates visitors, and deduplicates retries',async()=>{const db=database();const first=await api(new Request(base),db);const cookie=first.headers.get('set-cookie').split(';')[0];const post=()=>new Request(base,{method:'POST',headers:{cookie,origin:'http://localhost:4173'},body:JSON.stringify(payload)});assert.equal((await api(post(),db)).status,201);assert.equal((await api(post(),db)).status,200);const same=await(await api(new Request(base,{headers:{cookie}}),db)).json();assert.equal(same.results.length,1);assert.equal(same.results[0].character,resultFrom(payload.answers).character);const other=await(await api(new Request(base),db)).json();assert.equal(other.results.length,0);});
test('API rejects invalid answers, cross-origin posts and handles unavailable database',async()=>{const db=database();assert.equal((await api(new Request(base,{method:'POST',body:JSON.stringify({...payload,answers:[0]})}),db)).status,400);assert.equal((await api(new Request(base,{method:'POST',headers:{origin:'https://elsewhere.example'},body:JSON.stringify(payload)}),db)).status,403);assert.equal((await api(new Request(base),{prepare(){throw Error('test unavailable');}})).status,503);});

